# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: localhost
  username: edusouzas
  password: dany22
  pool: 5

development:
  <<: *default
  database: colchonet_development
test:
  <<: *default
  database: colchonet_test
production:
  <<: *default
  database: colchonet_production
